version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/dev_makefiles/api/Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
  app:
    build:
      context: .
      dockerfile: src/dev_makefiles/app/Dockerfile
    working_dir: /app
    ports:
      - "8501:8501"
  cli:
    build:
      context: .
      dockerfile: src/dev_makefiles/cli/Dockerfile
    working_dir: /app
  services:
    build:
      context: .
      dockerfile: src/dev_makefiles/services/Dockerfile
    working_dir: /app
